"""Shared validation limits, referenced by schemas, services, and the monitoring layer."""

MIN_INTERVAL_SECONDS = 30
MAX_INTERVAL_SECONDS = 24 * 60 * 60

MIN_TIMEOUT_SECONDS = 1
MAX_TIMEOUT_SECONDS = 60

MIN_STATUS_CODE = 100
MAX_STATUS_CODE = 599

MAX_NAME_LENGTH = 200
MAX_URL_LENGTH = 2048

MAX_HEADERS = 20
MAX_HEADER_KEY_LENGTH = 128
MAX_HEADER_VALUE_LENGTH = 2048

MAX_TAGS = 5
MAX_TAG_LENGTH = 30

MANUAL_CHECK_THROTTLE_SECONDS = 5
MAX_REDIRECTS = 5
